final task completed
VladimirTsodikov/omd pull request #5
Opened 2023-11-21 23:25 UTC by VladimirTsodikov

2023-11-23 15:43 UTC, ffix requested changes
Неплохо! Но есть что поправить


-     Написание читаемого и понятного кода — 2 (есть недостатки в логике, читаемости, нейминге)
-     Тщательное покрытие кода тестами — 1 (тесты есть, но покрыта только часть кода)
-     Свободное владение встроенными типами данных и знание их алгоритмических сложностей — 3
-     Разделение кода на функции, классы, модули — 1 (есть проблемы с наследованием и понимание работы классов).
-     Владением idea, git — 2 (PR и отдельная директория, но, всё же, хотелось бы выдеть историю коммитов в тестовом задании).
-     Понимание концепции декораторов — 1 (декоратор есть, но он реализован некорректно и не используется в коде)
-     Понимание основ функционального программирования — 2 (см. выше о декораторах)

Итого: 11/21

2023-11-23 15:43 UTC, ffix commented on Final/cli.py
> +        raise SyntaxError('Такой пиццы в данный момент нет в продаже')
Нехорошо пользователю наружу выбрасывать исключение, ну и тут не SyntaxError должен быть, это же не синтаксическая ошибка, а, вероятно, ValueError

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +            raise SyntaxError('Данная пицца не может иметь такой размер')
Не syntax error

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +    def var_sizes():
Не очень понятен нейминг — `var_size`.
И он дублируется в каждом объекте, правильнее вынести в базовый класс

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +        if size not in Margherita.var_sizes():
Эта проверка повторяется в каждом классе, хотя логично было бы положить её в базовый класс. И Обращаться корректнее к `self`, а не `Margherita`

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +        super().__init__("Margherita", size)
Правильнее положить название пиццы в атрибут класса, а не передавать его каждый раз в конструкторе

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +    def __init__(self, size: str):
Всё это правильнее унести в базовый класс

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +            case 'L':
Хорошая задумка, но размеры хорошо бы вынести куда-то (в атрибуты, например, а не хранить прямо в коде)

2023-11-23 15:43 UTC, ffix commented on Final/pizza_test.py
> +import unittest
Желательно использовать pytest

2023-11-23 15:43 UTC, ffix commented on Final/pizza_test.py
Нет тестов на логику приготовления пиццы, только на сами типы пицц

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +    def __eq__(self, __other: object) -> bool:
странный нейминг, просто `other`

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +        if self.name != __other.name:
а если справа у объекта нет атрибута name?

2023-11-23 15:43 UTC, ffix commented on Final/cli.py
> +    if (delivery):
скобки не нужны

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +def bake(pizza: Pizza):
эта функция не используется

2023-11-23 15:43 UTC, ffix commented on Final/cli.py
> +    print(f'🔥 Приготовили пиццу {pizza} в печи за {randint(10, 25)} мин!')
По условию, расчёт времени и шаблон должен быть реализован с использованием декораторов

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +        print(function_to_decorate.__name__, end=' ')
Не вполне понимаю что тут происходит и зачем мы печатаем имя функции, в задании это не требовалось

2023-11-23 15:43 UTC, ffix commented on Final/pizza.py
> +def log(function_to_decorate):
обычно называют просто func

2023-11-23 15:43 UTC, ffix commented on Final/cli.py
> +        print(f'- {subclass.__name__} {subclass.icon()} : доступные размеры: ', end='')
Лучше хранить название пиццы явно, а не обращаться к __name__

2023-11-23 15:43 UTC, ffix commented on Final/cli.py
> +    for subclass in Pizza.__subclasses__():
Не слишком эффективно, при большом количестве пицц это будет работать медленно

2023-11-26 11:08 UTC, VladimirTsodikov commented
@ffix Исправил замечания, посмотрите теперь, пожалуйста. Действительно, я неправильно понял некоторые задания, теперь разобрался. Спасибо за подробную обратную связь!!

2023-12-11 05:57 UTC, ffix approved these changes
Спасибо за исправления! Стало намного лучше.

По пункстам:

- Написание читаемого и понятного кода — 3
- Тщательное покрытие кода тестами — 2 (хорошо, но некоторая логика осталась не покрыта)
- Свободное владение встроенными типами данных и знание их алгоритмических сложностей — 3
- Разделение кода на функции, классы, модули — 2 (всё ещё есть проблемы с наследованием и понимание работы классов).
- Владением idea, git — 3
-Понимание концепции декораторов — 2 (несколько декораторов, хотя достаточно было 1го)
- Понимание основ функционального программирования — 3

Итого: 18/21 и - 1 балл за повторную сдачу, то есть 17.

2023-12-11 05:57 UTC, ffix commented on Final/pizza.py
> +                raise WrongPizzaSizeException
Не вполне понимаю зачем тут выкидывать исключение и ниже его ловить. Когда это происходит в рамках одной функции, это странно. Опять же, best practices по обработке исключений говорят нам, что блок try/except должен быть максимально короткий, тут же, он оборачивает всю функцию.

2023-12-11 05:57 UTC, ffix commented on Final/pizza.py
> +def log_delivery(func):
Декораторы идентичны, а значит, достаточно было одного `@log`

2023-12-11 05:57 UTC, ffix commented on Final/pizza.py
> +    def __init__(self, size: str):
этот блок не нужен, он ничего не делает

2023-12-11 05:57 UTC, ffix commented on Final/pizza.py
> +            return False
нужно `return NotImplemented`
https://jcalderone.livejournal.com/32837.html

2023-12-11 05:57 UTC, ffix commented on Final/cli.py
> +    for subclass in Pizza.__subclasses__():
А также, это выводит только непосредственных наследников

2023-12-11 05:57 UTC, ffix commented on Final/pizza_test.py
- Тестирование декораторов log_bake и log_delivery: Тесты не проверяют, корректно ли работают декораторы для логирования времени приготовления и доставки.
- Инициализация экземпляров класса Pizza: Нет тестов, проверяющих поведение при создании экземпляров с некорректными параметрами.

2023-12-21 10:17 UTC, merged